canton {
  domains {
    localdomain {
      storage {
        type = postgres
        config {
          dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
          properties = {
            serverName = "postgres"
            portNumber = "5432"
            databaseName = "canton_db"
            user = "canton"
            password = "canton_password"
          }
        }
      }
      public-api {
        port = 5028
        address = 0.0.0.0
      }
      admin-api {
        port = 5029
        address = 0.0.0.0
      }
    }
  }
}
